/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CardlistRouteImport } from './routes/cardlist'
import { Route as IndexRouteImport } from './routes/index'

const CardlistRoute = CardlistRouteImport.update({
  id: '/cardlist',
  path: '/cardlist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cardlist': typeof CardlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardlist': typeof CardlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cardlist': typeof CardlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cardlist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cardlist'
  id: '__root__' | '/' | '/cardlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardlistRoute: typeof CardlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cardlist': {
      id: '/cardlist'
      path: '/cardlist'
      fullPath: '/cardlist'
      preLoaderRoute: typeof CardlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardlistRoute: CardlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
