/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourceCounterRouteImport } from './routes/resource-counter'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as InfoRouteImport } from './routes/info'
import { Route as DecklistRouteImport } from './routes/decklist'
import { Route as CardlistRouteImport } from './routes/cardlist'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsMulliganRouteImport } from './routes/tools/mulligan'
import { Route as DeckDeckIdRouteImport } from './routes/deck/$deckId'

const ResourceCounterRoute = ResourceCounterRouteImport.update({
  id: '/resource-counter',
  path: '/resource-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const DecklistRoute = DecklistRouteImport.update({
  id: '/decklist',
  path: '/decklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CardlistRoute = CardlistRouteImport.update({
  id: '/cardlist',
  path: '/cardlist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMulliganRoute = ToolsMulliganRouteImport.update({
  id: '/tools/mulligan',
  path: '/tools/mulligan',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdRoute = DeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cardlist': typeof CardlistRoute
  '/decklist': typeof DecklistRoute
  '/info': typeof InfoRoute
  '/keywords': typeof KeywordsRoute
  '/resource-counter': typeof ResourceCounterRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/tools/mulligan': typeof ToolsMulliganRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardlist': typeof CardlistRoute
  '/decklist': typeof DecklistRoute
  '/info': typeof InfoRoute
  '/keywords': typeof KeywordsRoute
  '/resource-counter': typeof ResourceCounterRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/tools/mulligan': typeof ToolsMulliganRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cardlist': typeof CardlistRoute
  '/decklist': typeof DecklistRoute
  '/info': typeof InfoRoute
  '/keywords': typeof KeywordsRoute
  '/resource-counter': typeof ResourceCounterRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/tools/mulligan': typeof ToolsMulliganRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cardlist'
    | '/decklist'
    | '/info'
    | '/keywords'
    | '/resource-counter'
    | '/deck/$deckId'
    | '/tools/mulligan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cardlist'
    | '/decklist'
    | '/info'
    | '/keywords'
    | '/resource-counter'
    | '/deck/$deckId'
    | '/tools/mulligan'
  id:
    | '__root__'
    | '/'
    | '/cardlist'
    | '/decklist'
    | '/info'
    | '/keywords'
    | '/resource-counter'
    | '/deck/$deckId'
    | '/tools/mulligan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardlistRoute: typeof CardlistRoute
  DecklistRoute: typeof DecklistRoute
  InfoRoute: typeof InfoRoute
  KeywordsRoute: typeof KeywordsRoute
  ResourceCounterRoute: typeof ResourceCounterRoute
  DeckDeckIdRoute: typeof DeckDeckIdRoute
  ToolsMulliganRoute: typeof ToolsMulliganRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resource-counter': {
      id: '/resource-counter'
      path: '/resource-counter'
      fullPath: '/resource-counter'
      preLoaderRoute: typeof ResourceCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decklist': {
      id: '/decklist'
      path: '/decklist'
      fullPath: '/decklist'
      preLoaderRoute: typeof DecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardlist': {
      id: '/cardlist'
      path: '/cardlist'
      fullPath: '/cardlist'
      preLoaderRoute: typeof CardlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/mulligan': {
      id: '/tools/mulligan'
      path: '/tools/mulligan'
      fullPath: '/tools/mulligan'
      preLoaderRoute: typeof ToolsMulliganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId': {
      id: '/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardlistRoute: CardlistRoute,
  DecklistRoute: DecklistRoute,
  InfoRoute: InfoRoute,
  KeywordsRoute: KeywordsRoute,
  ResourceCounterRoute: ResourceCounterRoute,
  DeckDeckIdRoute: DeckDeckIdRoute,
  ToolsMulliganRoute: ToolsMulliganRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
