/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleRulesRouteImport } from './routes/$locale/rules'
import { Route as LocaleResourceCounterRouteImport } from './routes/$locale/resource-counter'
import { Route as LocaleKeywordsRouteImport } from './routes/$locale/keywords'
import { Route as LocaleInfoRouteImport } from './routes/$locale/info'
import { Route as LocaleDecklistRouteImport } from './routes/$locale/decklist'
import { Route as LocaleCardlistRouteImport } from './routes/$locale/cardlist'
import { Route as LocaleToolsMulliganRouteImport } from './routes/$locale/tools/mulligan'
import { Route as LocaleDeckDeckIdRouteImport } from './routes/$locale/deck/$deckId'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRulesRoute = LocaleRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleResourceCounterRoute = LocaleResourceCounterRouteImport.update({
  id: '/resource-counter',
  path: '/resource-counter',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleKeywordsRoute = LocaleKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleInfoRoute = LocaleInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDecklistRoute = LocaleDecklistRouteImport.update({
  id: '/decklist',
  path: '/decklist',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCardlistRoute = LocaleCardlistRouteImport.update({
  id: '/cardlist',
  path: '/cardlist',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleToolsMulliganRoute = LocaleToolsMulliganRouteImport.update({
  id: '/tools/mulligan',
  path: '/tools/mulligan',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDeckDeckIdRoute = LocaleDeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/cardlist': typeof LocaleCardlistRoute
  '/$locale/decklist': typeof LocaleDecklistRoute
  '/$locale/info': typeof LocaleInfoRoute
  '/$locale/keywords': typeof LocaleKeywordsRoute
  '/$locale/resource-counter': typeof LocaleResourceCounterRoute
  '/$locale/rules': typeof LocaleRulesRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/deck/$deckId': typeof LocaleDeckDeckIdRoute
  '/$locale/tools/mulligan': typeof LocaleToolsMulliganRoute
}
export interface FileRoutesByTo {
  '/$locale/cardlist': typeof LocaleCardlistRoute
  '/$locale/decklist': typeof LocaleDecklistRoute
  '/$locale/info': typeof LocaleInfoRoute
  '/$locale/keywords': typeof LocaleKeywordsRoute
  '/$locale/resource-counter': typeof LocaleResourceCounterRoute
  '/$locale/rules': typeof LocaleRulesRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/deck/$deckId': typeof LocaleDeckDeckIdRoute
  '/$locale/tools/mulligan': typeof LocaleToolsMulliganRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/cardlist': typeof LocaleCardlistRoute
  '/$locale/decklist': typeof LocaleDecklistRoute
  '/$locale/info': typeof LocaleInfoRoute
  '/$locale/keywords': typeof LocaleKeywordsRoute
  '/$locale/resource-counter': typeof LocaleResourceCounterRoute
  '/$locale/rules': typeof LocaleRulesRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/deck/$deckId': typeof LocaleDeckDeckIdRoute
  '/$locale/tools/mulligan': typeof LocaleToolsMulliganRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$locale'
    | '/$locale/cardlist'
    | '/$locale/decklist'
    | '/$locale/info'
    | '/$locale/keywords'
    | '/$locale/resource-counter'
    | '/$locale/rules'
    | '/$locale/'
    | '/$locale/deck/$deckId'
    | '/$locale/tools/mulligan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$locale/cardlist'
    | '/$locale/decklist'
    | '/$locale/info'
    | '/$locale/keywords'
    | '/$locale/resource-counter'
    | '/$locale/rules'
    | '/$locale'
    | '/$locale/deck/$deckId'
    | '/$locale/tools/mulligan'
  id:
    | '__root__'
    | '/$locale'
    | '/$locale/cardlist'
    | '/$locale/decklist'
    | '/$locale/info'
    | '/$locale/keywords'
    | '/$locale/resource-counter'
    | '/$locale/rules'
    | '/$locale/'
    | '/$locale/deck/$deckId'
    | '/$locale/tools/mulligan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/rules': {
      id: '/$locale/rules'
      path: '/rules'
      fullPath: '/$locale/rules'
      preLoaderRoute: typeof LocaleRulesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/resource-counter': {
      id: '/$locale/resource-counter'
      path: '/resource-counter'
      fullPath: '/$locale/resource-counter'
      preLoaderRoute: typeof LocaleResourceCounterRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/keywords': {
      id: '/$locale/keywords'
      path: '/keywords'
      fullPath: '/$locale/keywords'
      preLoaderRoute: typeof LocaleKeywordsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/info': {
      id: '/$locale/info'
      path: '/info'
      fullPath: '/$locale/info'
      preLoaderRoute: typeof LocaleInfoRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/decklist': {
      id: '/$locale/decklist'
      path: '/decklist'
      fullPath: '/$locale/decklist'
      preLoaderRoute: typeof LocaleDecklistRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/cardlist': {
      id: '/$locale/cardlist'
      path: '/cardlist'
      fullPath: '/$locale/cardlist'
      preLoaderRoute: typeof LocaleCardlistRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/tools/mulligan': {
      id: '/$locale/tools/mulligan'
      path: '/tools/mulligan'
      fullPath: '/$locale/tools/mulligan'
      preLoaderRoute: typeof LocaleToolsMulliganRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/deck/$deckId': {
      id: '/$locale/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/$locale/deck/$deckId'
      preLoaderRoute: typeof LocaleDeckDeckIdRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleCardlistRoute: typeof LocaleCardlistRoute
  LocaleDecklistRoute: typeof LocaleDecklistRoute
  LocaleInfoRoute: typeof LocaleInfoRoute
  LocaleKeywordsRoute: typeof LocaleKeywordsRoute
  LocaleResourceCounterRoute: typeof LocaleResourceCounterRoute
  LocaleRulesRoute: typeof LocaleRulesRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleDeckDeckIdRoute: typeof LocaleDeckDeckIdRoute
  LocaleToolsMulliganRoute: typeof LocaleToolsMulliganRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleCardlistRoute: LocaleCardlistRoute,
  LocaleDecklistRoute: LocaleDecklistRoute,
  LocaleInfoRoute: LocaleInfoRoute,
  LocaleKeywordsRoute: LocaleKeywordsRoute,
  LocaleResourceCounterRoute: LocaleResourceCounterRoute,
  LocaleRulesRoute: LocaleRulesRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleDeckDeckIdRoute: LocaleDeckDeckIdRoute,
  LocaleToolsMulliganRoute: LocaleToolsMulliganRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
